const nigerianStates = [
  { name: 'Abia', code: 'AB', capital: 'Umuahia', zone: 'South East' },
  { name: 'Adamawa', code: 'AD', capital: 'Yola', zone: 'North East' },
  { name: 'Akwa Ibom', code: 'AK', capital: 'Uyo', zone: 'South South' },
  { name: 'Anambra', code: 'AN', capital: 'Awka', zone: 'South East' },
  { name: 'Bauchi', code: 'BA', capital: 'Bauchi', zone: 'North East' },
  { name: 'Bayelsa', code: 'BY', capital: 'Yenagoa', zone: 'South South' },
  { name: 'Benue', code: 'BE', capital: 'Makurdi', zone: 'North Central' },
  { name: 'Borno', code: 'BO', capital: 'Maiduguri', zone: 'North East' },
  { name: 'Cross River', code: 'CR', capital: 'Calabar', zone: 'South South' },
  { name: 'Delta', code: 'DE', capital: 'Asaba', zone: 'South South' },
  { name: 'Ebonyi', code: 'EB', capital: 'Abakaliki', zone: 'South East' },
  { name: 'Edo', code: 'ED', capital: 'Benin City', zone: 'South South' },
  { name: 'Ekiti', code: 'EK', capital: 'Ado-Ekiti', zone: 'South West' },
  { name: 'Enugu', code: 'EN', capital: 'Enugu', zone: 'South East' },
  { name: 'FCT', code: 'FC', capital: 'Abuja', zone: 'North Central' },
  { name: 'Gombe', code: 'GO', capital: 'Gombe', zone: 'North East' },
  { name: 'Imo', code: 'IM', capital: 'Owerri', zone: 'South East' },
  { name: 'Jigawa', code: 'JI', capital: 'Dutse', zone: 'North West' },
  { name: 'Kaduna', code: 'KD', capital: 'Kaduna', zone: 'North West' },
  { name: 'Kano', code: 'KN', capital: 'Kano', zone: 'North West' },
  { name: 'Katsina', code: 'KT', capital: 'Katsina', zone: 'North West' },
  { name: 'Kebbi', code: 'KE', capital: 'Birnin Kebbi', zone: 'North West' },
  { name: 'Kogi', code: 'KO', capital: 'Lokoja', zone: 'North Central' },
  { name: 'Kwara', code: 'KW', capital: 'Ilorin', zone: 'North Central' },
  { name: 'Lagos', code: 'LA', capital: 'Ikeja', zone: 'South West' },
  { name: 'Nasarawa', code: 'NA', capital: 'Lafia', zone: 'North Central' },
  { name: 'Niger', code: 'NI', capital: 'Minna', zone: 'North Central' },
  { name: 'Ogun', code: 'OG', capital: 'Abeokuta', zone: 'South West' },
  { name: 'Ondo', code: 'ON', capital: 'Akure', zone: 'South West' },
  { name: 'Osun', code: 'OS', capital: 'Osogbo', zone: 'South West' },
  { name: 'Oyo', code: 'OY', capital: 'Ibadan', zone: 'South West' },
  { name: 'Plateau', code: 'PL', capital: 'Jos', zone: 'North Central' },
  { name: 'Rivers', code: 'RI', capital: 'Port Harcourt', zone: 'South South' },
  { name: 'Sokoto', code: 'SO', capital: 'Sokoto', zone: 'North West' },
  { name: 'Taraba', code: 'TA', capital: 'Jalingo', zone: 'North East' },
  { name: 'Yobe', code: 'YO', capital: 'Damaturu', zone: 'North East' },
  { name: 'Zamfara', code: 'ZA', capital: 'Gusau', zone: 'North West' }
];

module.exports = nigerianStates;
