const ROLE_PERMISSIONS = {
  admin: {
    canViewAllCases: true,
    canViewPayments: true,
    canViewReports: true,
    canManageUsers: true,
    canGenerateDocket: true,
    canAcknowledgeDocket: true,
    canViewProBono: true,
    canDocumentProBono: true,
    canFileCase: true,
    canAssignJudge: true,
    canTransferCase: true,
    canViewAllDashboards: true,
    canDeliverJudgment: true,
    canManageFees: true,
    dashboardSections: ['cases', 'payments', 'reports', 'users', 'dockets', 'probono', 'analytics', 'settings']
  },
  Justice: {
    canViewAllCases: true,
    canViewPayments: false,
    canViewReports: true,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: true,
    canViewProBono: true,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: true,
    canViewAllDashboards: false,
    canDeliverJudgment: true,
    canManageFees: false,
    dashboardSections: ['cases', 'dockets', 'probono', 'calendar', 'judgments']
  },
  judge: {
    canViewAllCases: false,
    canViewPayments: false,
    canViewReports: true,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: true,
    canViewProBono: true,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: true,
    canViewAllDashboards: false,
    canDeliverJudgment: true,
    canManageFees: false,
    dashboardSections: ['cases', 'dockets', 'probono', 'calendar', 'judgments']
  },
  'Chief Magistrate': {
    canViewAllCases: false,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: true,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: true,
    canViewAllDashboards: false,
    canDeliverJudgment: true,
    canManageFees: false,
    dashboardSections: ['cases', 'dockets', 'calendar', 'judgments']
  },
  Magistrate: {
    canViewAllCases: false,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: true,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: true,
    canViewAllDashboards: false,
    canDeliverJudgment: true,
    canManageFees: false,
    dashboardSections: ['cases', 'dockets', 'calendar', 'judgments']
  },
  prosecutor: {
    canViewAllCases: true,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: false,
    canViewProBono: true,
    canDocumentProBono: true,
    canFileCase: true,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: false,
    dashboardSections: ['cases', 'probono', 'calendar', 'documents']
  },
  clerk: {
    canViewAllCases: true,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: true,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: true,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: true,
    dashboardSections: ['cases', 'dockets', 'filing', 'calendar', 'fees']
  },
  registrar: {
    canViewAllCases: true,
    canViewPayments: true,
    canViewReports: true,
    canManageUsers: false,
    canGenerateDocket: true,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: true,
    canTransferCase: true,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: true,
    dashboardSections: ['cases', 'dockets', 'payments', 'calendar', 'assignments', 'registry']
  },
  litigation: {
    canViewAllCases: true,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: true,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: false,
    dashboardSections: ['cases', 'calendar', 'documents']
  },
  accountant: {
    canViewAllCases: false,
    canViewPayments: true,
    canViewReports: true,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: true,
    dashboardSections: ['payments', 'reports', 'fees']
  },
  cashier: {
    canViewAllCases: false,
    canViewPayments: true,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: true,
    dashboardSections: ['payments', 'fees']
  },
  record_officer: {
    canViewAllCases: true,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: false,
    dashboardSections: ['cases', 'reports', 'records']
  },
  bailiff: {
    canViewAllCases: false,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: false,
    dashboardSections: ['cases', 'calendar', 'service']
  },
  secretary: {
    canViewAllCases: false,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: false,
    dashboardSections: ['calendar', 'documents', 'correspondence']
  },
  court_reporter: {
    canViewAllCases: false,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: false,
    dashboardSections: ['cases', 'calendar', 'transcripts']
  },
  usher: {
    canViewAllCases: false,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: false,
    dashboardSections: ['calendar', 'courtroom']
  },
  security: {
    canViewAllCases: false,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: false,
    dashboardSections: ['access', 'logs']
  },
  librarian: {
    canViewAllCases: false,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: false,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: false,
    dashboardSections: ['library', 'resources']
  },
  probate: {
    canViewAllCases: false,
    canViewPayments: false,
    canViewReports: false,
    canManageUsers: false,
    canGenerateDocket: false,
    canAcknowledgeDocket: false,
    canViewProBono: false,
    canDocumentProBono: false,
    canFileCase: true,
    canAssignJudge: false,
    canTransferCase: false,
    canViewAllDashboards: false,
    canDeliverJudgment: false,
    canManageFees: true,
    dashboardSections: ['cases', 'filing', 'fees', 'calendar']
  }
};

function getPermissions(role) {
  return ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS.clerk;
}

function hasPermission(role, permission) {
  const perms = getPermissions(role);
  return !!perms[permission];
}

function getDashboardSections(role) {
  const perms = getPermissions(role);
  return perms.dashboardSections || [];
}

module.exports = { ROLE_PERMISSIONS, getPermissions, hasPermission, getDashboardSections };
