const User = require('../models/User');

const ROLE_PREFIXES = {
  Justice: 'JUS',
  Judge: 'JDG',
  'Chief Magistrate': 'CMG',
  Magistrate: 'MAG',
  'Chief Judge': 'CJG',
  admin: 'ADM',
  registrar: 'REG',
  clerk: 'CLK',
  accountant: 'ACT',
  bailiff: 'BLF',
  secretary: 'SEC',
  cashier: 'CSH',
  litigation: 'LIT',
  prosecutor: 'PRO',
  probate: 'PRB',
  record_officer: 'RCO',
  court_reporter: 'CRP',
  usher: 'USH',
  security: 'SCU',
  librarian: 'LIB'
};

const STATE_CODES = {
  'Abia': 'ABI',
  'Adamawa': 'ADA',
  'Akwa Ibom': 'AKW',
  'Anambra': 'ANA',
  'Bauchi': 'BAU',
  'Bayelsa': 'BAY',
  'Benue': 'BEN',
  'Borno': 'BOR',
  'Cross River': 'CRO',
  'Delta': 'DEL',
  'Ebonyi': 'EBO',
  'Edo': 'EDO',
  'Ekiti': 'EKI',
  'Enugu': 'ENU',
  'Gombe': 'GOM',
  'Imo': 'IMO',
  'Jigawa': 'JIG',
  'Kaduna': 'KAD',
  'Kano': 'KAN',
  'Katsina': 'KAT',
  'Kebbi': 'KEB',
  'Kogi': 'KOG',
  'Kwara': 'KWA',
  'Lagos': 'LAG',
  'Nasarawa': 'NAS',
  'Niger': 'NIG',
  'Ogun': 'OGU',
  'Ondo': 'OND',
  'Osun': 'OSO',
  'Oyo': 'OYO',
  'Plateau': 'PLA',
  'Rivers': 'RIV',
  'Sokoto': 'SOK',
  'Taraba': 'TAR',
  'Yobe': 'YOB',
  'Zamfara': 'ZAM',
  'FCT': 'FCT',
  'Abuja': 'ABU'
};

const LGA_CODES = {
  'Aba North': 'ABN',
  'Aba South': 'ABS',
  'Arochukwu': 'ARC',
  'Bende': 'BND',
  'Ikwuano': 'IKW',
  'Isiala Ngwa North': 'INN',
  'Isiala Ngwa South': 'INS',
  'Isuikwuato': 'ISK',
  'Obi Ngwa': 'OBG',
  'Ohafia': 'OHF',
  'Osisioma': 'OSM',
  'Ugwunagbo': 'UGW',
  'Ukwa East': 'UKE',
  'Ukwa West': 'UKW',
  'Umuahia North': 'UHN',
  'Umuahia South': 'UHS',
  'Umu Nneochi': 'UNC',
  'Demsa': 'DMS',
  'Fufure': 'FFR',
  'Ganye': 'GNY',
  'Gayuk': 'GYK',
  'Gombi': 'GMB',
  'Grie': 'GRI',
  'Hong': 'HNG',
  'Jada': 'JAD',
  'Larmurde': 'LRM',
  'Madagali': 'MDG',
  'Maiha': 'MAH',
  'Mayo Belwa': 'MBW',
  'Michika': 'MCH',
  'Mubi North': 'MBN',
  'Mubi South': 'MBS',
  'Numan': 'NMN',
  'Shelleng': 'SHL',
  'Song': 'SNG',
  'Toungo': 'TNG',
  'Yola North': 'YLN',
  'Yola South': 'YLS',
  'Abak': 'ABK',
  'Eastern Obolo': 'EOB',
  'Eket': 'EKT',
  'Esit Eket': 'EEK',
  'Essien Udim': 'ESU',
  'Etim Ekpo': 'ETE',
  'Etinan': 'ETN',
  'Ibeno': 'IBN',
  'Ibesikpo Asutan': 'IBK',
  'Ibiono-Ibom': 'IBI',
  'Ika': 'IKA',
  'Ikono': 'IKN',
  'Ikot Abasi': 'IKA',
  'Ikot Ekpene': 'IKE',
  'Ini': 'INI',
  'Itu': 'ITU',
  'Mbo': 'MBO',
  'Mkpat-Enin': 'MKE',
  'Nsit-Atai': 'NSA',
  'Nsit-Ibom': 'NSI',
  'Nsit-Ubium': 'NSU',
  'Obot Akara': 'OBA',
  'Okobo': 'OKB',
  'Onna': 'ONN',
  'Oron': 'ORN',
  'Oruk Anam': 'ORA',
  'Udung-Uko': 'UDU',
  'Ukanafun': 'UKF',
  'Uruan': 'URN',
  'Urue-Offong/Oruko': 'URO',
  'Uyo': 'UYO',
  'Aguata': 'AGT',
  'Anambra East': 'ANE',
  'Anambra West': 'ANW',
  'Anaocha': 'ANC',
  'Awka North': 'AWN',
  'Awka South': 'AWS',
  'Ayamelum': 'AYM',
  'Dunukofia': 'DNK',
  'Ekwusigo': 'EKW',
  'Idemili North': 'IDN',
  'Idemili South': 'IDS',
  'Ihiala': 'IHL',
  'Njikoka': 'NJK',
  'Nnewi North': 'NWN',
  'Nnewi South': 'NWS',
  'Ogbaru': 'OGB',
  'Onitsha North': 'OTN',
  'Onitsha South': 'OTS',
  'Orumba North': 'ORN',
  'Orumba South': 'ORS',
  'Oyi': 'OYI',
  'Alkaleria': 'ALK',
  'Bauchi': 'BAU',
  'Bogoro': 'BGR',
  'Damban': 'DMB',
  'Darazo': 'DRZ',
  'Dass': 'DAS',
  'Gamawa': 'GMW',
  'Ganjuwa': 'GNJ',
  'Giade': 'GID',
  'Itas/Gadau': 'ITG',
  'Jama\'are': 'JMR',
  'Katagum': 'KTG',
  'Kirfi': 'KRF',
  'Misau': 'MSA',
  'Ningi': 'NGI',
  'Shira': 'SHR',
  'Tafawa Balewa': 'TFB',
  'Toro': 'TOR',
  'Warji': 'WRJ',
  'Zaki': 'ZAK',
  'Brass': 'BRS',
  'Ekeremor': 'EKR',
  'Kolokuma/Opokuma': 'KLO',
  'Nembe': 'NMB',
  'Ogbia': 'OGB',
  'Sagbama': 'SGB',
  'Southern Ijaw': 'SIJ',
  'Yenagoa': 'YNG',
  'Apa': 'APA',
  'Ado': 'ADO',
  'Buruku': 'BRK',
  'Gboko': 'GBK',
  'Guma': 'GUM',
  'Gwer East': 'GWE',
  'Gwer West': 'GWW',
  'Katsina-Ala': 'KTA',
  'Konshisha': 'KNS',
  'Kwande': 'KWD',
  'Logo': 'LGO',
  'Makurdi': 'MKD',
  'Obi': 'OBI',
  'Ogbadigba': 'OGB',
  'Ohimini': 'OHM',
  'Oju': 'OJU',
  'Okpokwu': 'OKP',
  'Oturkpo': 'OTK',
  'Tarka': 'TRK',
  'Ukum': 'UKM',
  'Ushongo': 'USH',
  'Vandeikya': 'VDK',
  'Askira/Uba': 'ASK',
  'Bama': 'BAM',
  'Bayo': 'BAY',
  'Biu': 'BIU',
  'Chibok': 'CHB',
  'Damboa': 'DMB',
  'Dikwa': 'DKW',
  'Gubio': 'GBO',
  'Guzamala': 'GZM',
  'Gwoza': 'GWZ',
  'Hawul': 'HWL',
  'Jere': 'JRE',
  'Kaga': 'KAG',
  'Kala/Balge': 'KLB',
  'Konduga': 'KND',
  'Kukawa': 'KKW',
  'Kwaya Kusar': 'KWK',
  'Mafa': 'MFA',
  'Magumeri': 'MGM',
  'Maiduguri': 'MDG',
  'Marte': 'MRT',
  'Mobbar': 'MBB',
  'Monguno': 'MGN',
  'Ngala': 'NGL',
  'Nganzai': 'NGZ',
  'Shani': 'SHN',
  'Abi': 'ABI',
  'Akamkpa': 'AKM',
  'Akpabuyo': 'AKB',
  'Bekwarra': 'BKW',
  'Biase': 'BIS',
  'Boki': 'BOK',
  'Calabar Municipal': 'CBM',
  'Calabar South': 'CBS',
  'Etung': 'ETG',
  'Ikom': 'IKM',
  'Obanliku': 'OBL',
  'Obubra': 'OBB',
  'Obudu': 'OBD',
  'Odukpani': 'ODK',
  'Ogoja': 'OGO',
  'Yakurr': 'YKR',
  'Yala': 'YLA',
  'Aniocha North': 'ANN',
  'Aniocha South': 'ANS',
  'Bomadi': 'BMD',
  'Burutu': 'BRT',
  'Ethiope East': 'ETE',
  'Ethiope West': 'ETW',
  'Ika North East': 'IKE',
  'Ika South': 'IKS',
  'Isoko North': 'ISN',
  'Isoko South': 'ISS',
  'Ndokwa East': 'NDE',
  'Ndokwa West': 'NDW',
  'Okpe': 'OKP',
  'Oshimili North': 'OSN',
  'Oshimili South': 'OSS',
  'Patani': 'PTN',
  'Sapele': 'SPL',
  'Udu': 'UDU',
  'Ughelli North': 'UGH',
  'Ughelli South': 'UGS',
  'Ukwuani': 'UKW',
  'Uvwie': 'UVW',
  'Warri North': 'WRN',
  'Warri South': 'WRS',
  'Warri South West': 'RSW',
  'Abakaliki': 'ABK',
  'Afikpo North': 'AFN',
  'Afikpo South': 'AFS',
  'Ebonyi': 'EBO',
  'Ezza North': 'EZN',
  'Ezza South': 'EZS',
  'Ikwo': 'IKW',
  'Ishielu': 'ISH',
  'Ivo': 'IVO',
  'Izzi': 'IZZ',
  'Ohaozara': 'OHZ',
  'Ohaukwu': 'OHK',
  'Onicha': 'ONC',
  'Akoko-Edo': 'AKE',
  'Egor': 'EGR',
  'Esan Central': 'ESC',
  'Esan North-East': 'ESN',
  'Esan South-East': 'ESS',
  'Esan West': 'ESW',
  'Etsako Central': 'ETC',
  'Etsako East': 'ETE',
  'Etsako West': 'ETW',
  'Igueben': 'IGB',
  'Ikpoba-Okha': 'IKP',
  'Oredo': 'ORD',
  'Orhionmwon': 'ORH',
  'Ovia North-East': 'OVN',
  'Ovia South-West': 'OVS',
  'Owan East': 'OWE',
  'Owan West': 'OWW',
  'Uhunmwonde': 'UHW',
  'Ado Ekiti': 'ADE',
  'Efon': 'EFN',
  'Ekiti East': 'EKE',
  'Ekiti South-West': 'ESW',
  'Ekiti West': 'EKW',
  'Emure': 'EMR',
  'Gbonyin': 'GBN',
  'Ido Osi': 'IDS',
  'Ijero': 'IJR',
  'Ikere': 'IKR',
  'Ikole': 'IKL',
  'Ilejemeje': 'ILJ',
  'Irepodun/Ifelodun': 'IRF',
  'Ise/Orun': 'ISO',
  'Moba': 'MOB',
  'Oye': 'OYE',
  'Aninri': 'ANR',
  'Awgu': 'AWG',
  'Enugu East': 'ENE',
  'Enugu North': 'ENN',
  'Enugu South': 'ENS',
  'Ezeagu': 'EZG',
  'Igbo Etite': 'IGE',
  'Igbo Eze North': 'IGN',
  'Igbo Eze South': 'IGS',
  'Isi Uzo': 'ISU',
  'Nkanu East': 'NKE',
  'Nkanu West': 'NKW',
  'Nsukka': 'NSK',
  'Oji River': 'OJR',
  'Udenu': 'UDN',
  'Udi': 'UDI',
  'Uzo Uwani': 'UZW',
  'Abuja Municipal': 'ABJ',
  'Bwari': 'BWR',
  'Gwagwalada': 'GWA',
  'Kuje': 'KUJ',
  'Kwali': 'KWL',
  'Akko': 'AKO',
  'Balanga': 'BLG',
  'Billiri': 'BLR',
  'Dukku': 'DKU',
  'Funakaye': 'FNK',
  'Gombe': 'GOM',
  'Kaltungo': 'KLT',
  'Kwami': 'KWM',
  'Nafada': 'NFD',
  'Shomgom': 'SHG',
  'Yamaltu/Deba': 'YMD',
  'Ahiazu Mbaise': 'AHM',
  'Ehime Mbano': 'EHM',
  'Ezinihitte': 'EZN',
  'Ideato North': 'IDN',
  'Ideato South': 'IDS',
  'Ihitte/Uboma': 'IHU',
  'Ikeduru': 'IKD',
  'Isiala Mbana': 'ISM',
  'Isu': 'ISU',
  'Mbaitoli': 'MBT',
  'Ngor Okpala': 'NGO',
  'Njaba': 'NJB',
  'Nkwerre': 'NKR',
  'Nwangele': 'NWG',
  'Obowo': 'OBW',
  'Oguta': 'OGT',
  'Ohaji/Egbema': 'OHJ',
  'Okigwe': 'OKG',
  'Onuimo': 'ONM',
  'Orlu': 'ORL',
  'Orsu': 'ORS',
  'Oru East': 'ORE',
  'Oru West': 'ORW',
  'Owerri Municipal': 'OWM',
  'Owerri North': 'OWN',
  'Owerri West': 'OWW',
  'Unuimo': 'UNM',
  'Auyo': 'AUY',
  'Babura': 'BAB',
  'Biriniwa': 'BRW',
  'Birnin Kudu': 'BRK',
  'Buji': 'BUJ',
  'Dutse': 'DUT',
  'Gagarawa': 'GGR',
  'Garki': 'GRK',
  'Gumel': 'GML',
  'Guri': 'GUR',
  'Gwaram': 'GWR',
  'Gwiwa': 'GWI',
  'Hadejia': 'HDJ',
  'Jahun': 'JHN',
  'Kafin Hausa': 'KFH',
  'Kaugama': 'KGM',
  'Kazaure': 'KZR',
  'Kiri Kasama': 'KRK',
  'Kiyawa': 'KYW',
  'Maigatari': 'MGT',
  'Malam Madori': 'MLM',
  'Miga': 'MIG',
  'Ringim': 'RNG',
  'Roni': 'RON',
  'Sule Tankarkar': 'STK',
  'Taura': 'TAR',
  'Yankwashi': 'YKW',
  'Birnin Gwari': 'BGW',
  'Chikun': 'CHK',
  'Giwa': 'GIW',
  'Igabi': 'IGB',
  'Ikara': 'IKR',
  'Jaba': 'JAB',
  'Jema\'a': 'JMA',
  'Kachia': 'KAC',
  'Kaduna North': 'KDN',
  'Kaduna South': 'KDS',
  'Kagarko': 'KGK',
  'Kajuru': 'KJR',
  'Kaura': 'KRA',
  'Kauru': 'KRU',
  'Kubau': 'KUB',
  'Kudan': 'KUD',
  'Lere': 'LRE',
  'Makarfi': 'MKF',
  'Sabon Gari': 'SBG',
  'Sanga': 'SNG',
  'Soba': 'SOB',
  'Zangon Kataf': 'ZKF',
  'Zaria': 'ZAR',
  'Ajingi': 'AJI',
  'Albasu': 'ALS',
  'Bagwai': 'BGW',
  'Bebeji': 'BEB',
  'Bichi': 'BIC',
  'Bunkure': 'BNK',
  'Dala': 'DAL',
  'Dambatta': 'DMB',
  'Dawakin Kudu': 'DWK',
  'Dawakin Tofa': 'DWT',
  'Doguwa': 'DGW',
  'Fagge': 'FGG',
  'Gabasawa': 'GBS',
  'Garko': 'GRK',
  'Garun Mallam': 'GRM',
  'Gaya': 'GAY',
  'Gezawa': 'GZW',
  'Gwale': 'GWL',
  'Gwarzo': 'GWZ',
  'Kabo': 'KAB',
  'Kano Municipal': 'KNM',
  'Karaye': 'KRY',
  'Kibiya': 'KBY',
  'Kiru': 'KRU',
  'Kumbotso': 'KMB',
  'Kunchi': 'KNC',
  'Kura': 'KRA',
  'Madobi': 'MDB',
  'Makoda': 'MKD',
  'Minjibir': 'MJB',
  'Nasarawa': 'NSR',
  'Rano': 'RAN',
  'Rimin Gado': 'RMG',
  'Rogo': 'ROG',
  'Shanono': 'SHN',
  'Sumaila': 'SML',
  'Takai': 'TKA',
  'Tarauni': 'TRN',
  'Tofa': 'TOF',
  'Tsanyawa': 'TSY',
  'Tudun Wada': 'TDW',
  'Ungogo': 'UNG',
  'Warawa': 'WRW',
  'Wudil': 'WDL',
  'Bakori': 'BKR',
  'Batagarawa': 'BTG',
  'Batsari': 'BTS',
  'Baure': 'BRE',
  'Bindawa': 'BDW',
  'Charanchi': 'CHC',
  'Dandume': 'DNM',
  'Danja': 'DNJ',
  'Dan Musa': 'DNS',
  'Daura': 'DRA',
  'Dutsi': 'DTS',
  'Dutsin Ma': 'DTM',
  'Faskari': 'FSK',
  'Funtua': 'FNT',
  'Ingawa': 'ING',
  'Jibia': 'JBA',
  'Kafur': 'KFR',
  'Kaita': 'KTA',
  'Kankara': 'KNK',
  'Kankia': 'KNK',
  'Katsina': 'KTS',
  'Kurfi': 'KRF',
  'Kusada': 'KSD',
  'Mai\'Adua': 'MAD',
  'Malumfashi': 'MLF',
  'Mani': 'MAN',
  'Mashi': 'MSH',
  'Matazu': 'MTZ',
  'Musawa': 'MSW',
  'Rimi': 'RMI',
  'Sabuwa': 'SBW',
  'Safana': 'SFN',
  'Sandamu': 'SDM',
  'Zango': 'ZNG',
  'Aleiro': 'ALR',
  'Arewa Dandi': 'ARD',
  'Argungu': 'ARG',
  'Augie': 'AUG',
  'Bagudo': 'BGD',
  'Birnin Kebbi': 'BKB',
  'Bunza': 'BNZ',
  'Dandi': 'DND',
  'Fakai': 'FKY',
  'Gwandu': 'GWD',
  'Jega': 'JGA',
  'Kalgo': 'KLG',
  'Koko/Besse': 'KKB',
  'Maiyama': 'MYM',
  'Ngaski': 'NGK',
  'Sakaba': 'SKB',
  'Shanga': 'SHG',
  'Suru': 'SUR',
  'Wasagu/Danko': 'WSD',
  'Yauri': 'YRI',
  'Zuru': 'ZUR',
  'Adavi': 'ADV',
  'Ajaokuta': 'AJK',
  'Ankpa': 'ANK',
  'Bassa': 'BAS',
  'Dekina': 'DKN',
  'Ibaji': 'IBJ',
  'Idah': 'IDH',
  'Igalamela-Odolu': 'IGL',
  'Ijumu': 'IJM',
  'Kabba/Bunu': 'KBB',
  'Kogi': 'KOG',
  'Koto Karu': 'KTK',
  'Lokoja': 'LKJ',
  'Mopa Muro': 'MPM',
  'Ofu': 'OFU',
  'Ogori/Magongo': 'OGM',
  'Okehi': 'OKH',
  'Okene': 'OKN',
  'Olamaboro': 'OLB',
  'Omala': 'OML',
  'Yagba East': 'YGE',
  'Yagba West': 'YGW',
  'Agege': 'AGE',
  'Ajeromi-Ifelodun': 'AJF',
  'Alimosho': 'ALM',
  'Amuwo-Odofin': 'AMW',
  'Apapa': 'APA',
  'Badagry': 'BDG',
  'Epe': 'EPE',
  'Eti Osa': 'ETO',
  'Ibeju-Lekki': 'IBL',
  'Ifako-Ijaiye': 'IFK',
  'Ikeja': 'IKJ',
  'Ikorodu': 'IKR',
  'Kosofe': 'KSF',
  'Lagos Island': 'LGI',
  'Lagos Mainland': 'LGM',
  'Mushin': 'MSH',
  'Ojo': 'OJO',
  'Oshodi-Isolo': 'OSH',
  'Shomolu': 'SHM',
  'Surulere': 'SRL',
  'Akwanga': 'AKW',
  'Awe': 'AWE',
  'Doma': 'DOM',
  'Karu': 'KAR',
  'Keana': 'KEA',
  'Keffi': 'KFF',
  'Kokona': 'KKN',
  'Lafia': 'LAF',
  'Nasarawa': 'NSR',
  'Nasarawa Egon': 'NSE',
  'Obi': 'OBI',
  'Toto': 'TOT',
  'Wamba': 'WMB',
  'Agaie': 'AGI',
  'Agwara': 'AGW',
  'Bida': 'BID',
  'Borgu': 'BRG',
  'Bosso': 'BSS',
  'Chanchaga': 'CNC',
  'Edati': 'EDT',
  'Gbako': 'GBK',
  'Gurara': 'GRR',
  'Katcha': 'KTC',
  'Kontagora': 'KTG',
  'Lapai': 'LPA',
  'Lavun': 'LVN',
  'Magama': 'MGM',
  'Mariga': 'MRG',
  'Mashegu': 'MSG',
  'Mokwa': 'MKW',
  'Muya': 'MUY',
  'Paikoro': 'PKR',
  'Rafi': 'RAF',
  'Rijau': 'RJA',
  'Shiroro': 'SHR',
  'Suleja': 'SLJ',
  'Tafa': 'TAF',
  'Wushishi': 'WSH',
  'Abeokuta North': 'ABN',
  'Abeokuta South': 'ABS',
  'Ado-Odo/Ota': 'ADO',
  'Egbado North': 'EBN',
  'Egbado South': 'EBS',
  'Ewekoro': 'EWK',
  'Ifo': 'IFO',
  'Ijebu East': 'IJE',
  'Ijebu North': 'IJN',
  'Ijebu North East': 'IJNE',
  'Ijebu Ode': 'IJO',
  'Ikenne': 'IKN',
  'Imeko Afon': 'IME',
  'Ipokia': 'IPK',
  'Obafemi Owode': 'OBO',
  'Odeda': 'ODD',
  'Odogbolu': 'ODG',
  'Ogun Waterside': 'OGW',
  'Remo North': 'RMN',
  'Shagamu': 'SGM',
  'Akoko North East': 'AKN',
  'Akoko North West': 'AKW',
  'Akoko South East': 'AKS',
  'Akoko South West': 'AKW',
  'Akure North': 'AKN',
  'Akure South': 'AKS',
  'Ese Odo': 'ESD',
  'Idanre': 'IDR',
  'Ifedore': 'IFD',
  'Ilaje': 'ILJ',
  'Ile Oluji/Okeigbo': 'ILO',
  'Irele': 'IRL',
  'Odigbo': 'ODG',
  'Okitipupa': 'OKT',
  'Ondo East': 'OND',
  'Ondo West': 'ONW',
  'Ose': 'OSE',
  'Owo': 'OWO',
  'Aiyedaade': 'AYD',
  'Aiyedire': 'AYR',
  'Atakunmosa East': 'ATE',
  'Atakunmosa West': 'ATW',
  'Boluwaduro': 'BLW',
  'Boripe': 'BRP',
  'Ede North': 'EDN',
  'Ede South': 'EDS',
  'Egbedore': 'EGB',
  'Ejigbo': 'EJG',
  'Ife Central': 'IFC',
  'Ife East': 'IFE',
  'Ife North': 'IFN',
  'Ife South': 'IFS',
  'Ifedayo': 'IFD',
  'Ifelodun': 'IFL',
  'Ila': 'ILA',
  'Ilesa East': 'ILE',
  'Ilesa West': 'ILW',
  'Irepodun': 'IRD',
  'Irewole': 'IRW',
  'Isokan': 'ISK',
  'Iwo': 'IWO',
  'Obokun': 'OBK',
  'Odo Otin': 'ODO',
  'Ola Oluwa': 'OLO',
  'Olorunda': 'OLR',
  'Oriade': 'ORI',
  'Orolu': 'ORL',
  'Osogbo': 'OSO',
  'Afijio': 'AFJ',
  'Akinyele': 'AKY',
  'Atiba': 'ATB',
  'Atisbo': 'ATS',
  'Egbeda': 'EGB',
  'Ibadan North': 'IBN',
  'Ibadan North East': 'IBNE',
  'Ibadan North West': 'IBNW',
  'Ibadan South East': 'IBSE',
  'Ibadan South West': 'IBSW',
  'Ibarapa Central': 'IBR',
  'Ibarapa East': 'IBE',
  'Ibarapa North': 'IBN',
  'Ido': 'IDO',
  'Irepo': 'IRP',
  'Iseyin': 'ISY',
  'Itesiwaju': 'ITJ',
  'Iwajowa': 'IWJ',
  'Kajola': 'KJL',
  'Lagelu': 'LGL',
  'Ogbomosho North': 'OGN',
  'Ogbomosho South': 'OGS',
  'Ogo Oluwa': 'OGO',
  'Olorunsogo': 'OLR',
  'Oluyole': 'OLY',
  'Ona Ara': 'ONA',
  'Orelope': 'ORP',
  'Ori Ire': 'ORI',
  'Oyo East': 'OYE',
  'Oyo West': 'OYW',
  'Saki East': 'SKE',
  'Saki West': 'SKW',
  'Surulere': 'SRL',
  'Barkin Ladi': 'BRL',
  'Bassa': 'BAS',
  'Bokkos': 'BKS',
  'Jos East': 'JSE',
  'Jos North': 'JSN',
  'Jos South': 'JSS',
  'Kanam': 'KNM',
  'Kanke': 'KNK',
  'Langtang North': 'LTN',
  'Langtang South': 'LTS',
  'Mangu': 'MNG',
  'Mikang': 'MKG',
  'Pankshin': 'PKN',
  'Qua\'an Pan': 'QAP',
  'Riyom': 'RYM',
  'Shendam': 'SHD',
  'Wase': 'WSE',
  'Abua/Odual': 'ABD',
  'Ahoada East': 'AHE',
  'Ahoada West': 'AHW',
  'Akuku-Toru': 'AKT',
  'Andoni': 'AND',
  'Asari-Toru': 'AST',
  'Bonny': 'BNY',
  'Degema': 'DGM',
  'Eleme': 'ELM',
  'Emohua': 'EMH',
  'Etche': 'ETC',
  'Gokana': 'GKN',
  'Ikwerre': 'IKW',
  'Khana': 'KHA',
  'Obio/Akpor': 'OBA',
  'Ogba/Egbema/Ndoni': 'OEN',
  'Ogu/Bolo': 'OGB',
  'Okrika': 'OKR',
  'Omuma': 'OMM',
  'Opobo/Nkoro': 'OPN',
  'Oyigbo': 'OYG',
  'Port Harcourt': 'PHC',
  'Tai': 'TAI',
  'Binji': 'BNJ',
  'Bodinga': 'BDG',
  'Dange Shuni': 'DGS',
  'Gada': 'GAD',
  'Goronyo': 'GRY',
  'Gudu': 'GUD',
  'Gwadabawa': 'GWD',
  'Illela': 'ILL',
  'Isa': 'ISA',
  'Kebbe': 'KEB',
  'Kware': 'KWR',
  'Rabah': 'RAB',
  'Sabon Birni': 'SBB',
  'Shagari': 'SHG',
  'Silame': 'SLM',
  'Sokoto North': 'SKN',
  'Sokoto South': 'SKS',
  'Tambuwal': 'TBW',
  'Tangaza': 'TGZ',
  'Tureta': 'TRT',
  'Wamako': 'WMK',
  'Wurno': 'WRN',
  'Yabo': 'YAB',
  'Ardo Kola': 'ARK',
  'Bali': 'BAL',
  'Donga': 'DNG',
  'Gashaka': 'GSK',
  'Gassol': 'GSL',
  'Ibi': 'IBI',
  'Jalingo': 'JLG',
  'Karim Lamido': 'KRL',
  'Kumi': 'KMU',
  'Lau': 'LAU',
  'Sardauna': 'SRD',
  'Takum': 'TKM',
  'Ussa': 'USS',
  'Wukari': 'WKR',
  'Yorro': 'YRR',
  'Zing': 'ZNG',
  'Bursari': 'BRS',
  'Damaturu': 'DMT',
  'Fika': 'FKA',
  'Fune': 'FNE',
  'Geidam': 'GDM',
  'Gujba': 'GJB',
  'Gulani': 'GLN',
  'Jakusko': 'JKS',
  'Karasuwa': 'KRS',
  'Machina': 'MCN',
  'Nangere': 'NGR',
  'Nguru': 'NGR',
  'Potiskum': 'PTK',
  'Tarmuwa': 'TMW',
  'Yunusari': 'YNS',
  'Yusufari': 'YSF',
  'Anka': 'ANK',
  'Bakura': 'BKR',
  'Birnin Magaji/Kiyaw': 'BMK',
  'Bungudu': 'BGD',
  'Gummi': 'GMM',
  'Gusau': 'GSA',
  'Kaura Namoda': 'KRN',
  'Maradun': 'MRD',
  'Maru': 'MRU',
  'Shinkafi': 'SKF',
  'Talata Mafara': 'TMF',
  'Tsafe': 'TSF',
  'Zurmi': 'ZRM'
};

function getStateCode(state) {
  if (!state) return 'XXX';
  const code = STATE_CODES[state];
  if (code) return code;
  const keys = Object.keys(STATE_CODES);
  const match = keys.find(k => k.toLowerCase() === state.toLowerCase());
  return match ? STATE_CODES[match] : state.substring(0, 3).toUpperCase();
}

function getLgaCode(lga) {
  if (!lga) return 'XXX';
  const code = LGA_CODES[lga];
  if (code) return code;
  const keys = Object.keys(LGA_CODES);
  const match = keys.find(k => k.toLowerCase() === lga.toLowerCase());
  return match ? LGA_CODES[match] : lga.substring(0, 3).toUpperCase();
}

function getRolePrefix(role, title) {
  if (title && ROLE_PREFIXES[title]) return ROLE_PREFIXES[title];
  if (role && ROLE_PREFIXES[role]) return ROLE_PREFIXES[role];
  return 'STF';
}

function generateRandomSegment() {
  return String(Math.floor(Math.random() * 9000) + 1000);
}

async function generateStaffId(role, state, lga, title) {
  const prefix = getRolePrefix(role, title);
  const stateCode = getStateCode(state);
  const lgaCode = getLgaCode(lga);
  
  // Try up to 10 times with random generation
  for (let i = 0; i < 10; i++) {
    const random = generateRandomSegment();
    const staffId = `${prefix}-${stateCode}-${lgaCode}-${random}`;
    
    const existing = await User.findOne({ staffId });
    if (!existing) {
      return staffId;
    }
  }
  
  // If we've tried 10 times and found conflicts each time,
  // let's check a batch of candidates to find an available one more efficiently
  const batchSize = 20;
  const candidates = [];
  
  for (let i = 0; i < batchSize; i++) {
    const random = generateRandomSegment();
    candidates.push(`${prefix}-${stateCode}-${lgaCode}-${random}`);
  }
  
  // Check which candidates already exist
  const existingRecords = await User.find({ staffId: { $in: candidates } });
  const existingIds = new Set(existingRecords.map(record => record.staffId));
  
  // Find the first candidate that doesn't exist
  for (const candidate of candidates) {
    if (!existingIds.has(candidate)) {
      return candidate;
    }
  }
  
  // If all candidates in the batch are taken, try one more time with random
  // This is unlikely but possible if >90% of the space is taken
  const random = generateRandomSegment();
  return `${prefix}-${stateCode}-${lgaCode}-${random}`;
}

function validateStaffIdFormat(staffId) {
  const pattern = /^[A-Z]{3}-[A-Z]{3}-[A-Z]{3}-\d{4}$/;
  return pattern.test(staffId);
}

function getStaffIdPrefixInfo(staffId) {
  if (!staffId || !validateStaffIdFormat(staffId)) return null;
  const parts = staffId.split('-');
  return {
    prefix: parts[0],
    stateCode: parts[1],
    lgaCode: parts[2],
    random: parts[3]
  };
}

module.exports = {
  generateStaffId,
  validateStaffIdFormat,
  getStaffIdPrefixInfo,
  getRolePrefix,
  getStateCode,
  getLgaCode,
  ROLE_PREFIXES,
  STATE_CODES,
  LGA_CODES
};
